language: php
php:
  - '7.4snapshot'
before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source
script:
    - vendor/bin/phpunit
after_success:
- bash <(curl -s https://codecov.io/bash)
